#!/usr/bin/env bash

# Name: const
# Desc: an auto web server installation tool
# Date: 2013-02-07 by garryshield

clear

# Check if user is root
if [ $(id -u) != "0" ]; then
  echo "Error: You must be root to run this script."
  exit 1
fi

TOY="toy-1.0.0"

# Header prompt
echo "================================================================================"
echo "${TOY}"
echo "auto web server installation tool"
echo "================================================================================"

# Constant
ToyPath=$(pwd)
ToySrcPath=${ToyPath}/src
ToyTmpPath=${ToyPath}/tmp
ToyCnfPath=${ToyPath}/cnf

mkdir -p ${ToySrcPath}
mkdir -p ${ToyTmpPath}
mkdir -p ${ToyCnfPath}

ToySoftPath=/usr/local
ToySitesPath=/var/sites