#!/usr/bin/env bash

# Name: funcs;
# Desc: an auto web server installation tool;
# Date: 2013-02-07 by garryshield;

function install_lsb {
  echo "[+] Installing lsb..."
  if [ "$PM" = "yum" ]; then
    yum -y install redhat-lsb
  elif [ "$PM" = "apt" ]; then
    apt-get update
    apt-get --no-install-recommends install -y lsb-release
  fi
}

if grep -Eqi "CentOS" /etc/issue || grep -Eq "CentOS" /etc/*-release; then
  DIST_NAME='CentOS'
  PM='yum'
elif grep -Eqi "Red Hat Enterprise Linux Server" /etc/issue || grep -Eq "Red Hat Enterprise Linux Server" /etc/*-release; then
  DIST_NAME='RHEL'
  PM='yum'
elif grep -Eqi "Fedora" /etc/issue || grep -Eq "Fedora" /etc/*-release; then
  DIST_NAME='Fedora'
  PM='yum'
elif grep -Eqi "Ubuntu" /etc/issue || grep -Eq "Ubuntu" /etc/*-release; then
  DIST_NAME='Ubuntu'
  PM='apt'
elif grep -Eqi "Debian" /etc/issue || grep -Eq "Debian" /etc/*-release; then
  DIST_NAME='Debian'
  PM='apt'
else
  DIST_NAME='unknow'
  PM='unknow'
fi

KERNEL_NAME=`uname -s`
KERNEL_RELEASE=`uname -r`
MACHINE=`uname -m`

if [ -s /usr/bin/python3 ]; then
  DIST_RELEASE=`/usr/bin/python3 -c 'import platform; print(platform.linux_distribution()[1])'`
elif [ -s /usr/bin/python2 ]; then
  DIST_RELEASE=`/usr/bin/python2 -c 'import platform; print platform.linux_distribution()[1]'`
fi
if [ $? -ne 0 ]; then
  install_lsb
  DIST_RELEASE=`lsb_release -rs`
fi

if [[ `getconf WORD_BIT` = '32' && `getconf LONG_BIT` = '64' ]] ; then
    IS_64BIT='y'
else
    IS_64BIT='n'
fi

if uname -m | grep -Eqi "arm|aarch64"; then
    IS_ARM='y'
fi

function is_user_exists {
	if [ $# -ne 1 ]; then
		echo "Error: You must input a user name to check.";
		return 1;
	fi;
	if [ ! -z `grep "^$1" /etc/passwd|awk -F : "{print $3}"` ]; then
		# User exists
		# sed -n /$1/p /etc/passwd;
		grep $1 /etc/passwd;
		return 0;
	else
		# User not exists
		return 2;
	fi;
}

function is_group_exists {
	if [ $# -ne 1 ]; then
		echo "Error: You must input a greoup name to check.";
		return 1;
	fi;

	if [ ! -z `grep "^$1" /etc/group|awk -F : "{print $3}"` ]; then
		# Group exists
		# sed -n /$1/p /etc/group;
		grep $1 /etc/group;
		return 0;
	else
		# Group not exists
		return 2;
	fi;
}

function remove_user {
	if [ $# -ne 1 ]; then
		echo "Error: You must input a user name to remove.";
		exit 1;
	fi;

	is_user_exists $1;
	if [ $? -eq 0 ]; then
		# userdel -f -r $1 > /dev/null 2>&1 && echo "userdel -f -r $1 success";
		userdel $1 > /dev/null 2>&1 && echo "userdel -f -r $1 success";
		return 0;
	fi;
}

function remove_group  {
	if [ $# -ne 1 ]; then
		echo "Error: You must input a group name to remove.";
		exit 1;
	fi;

	is_group_exists $1;
	if [ $? -eq 0 ]; then
		groupdel $1 > /dev/null 2>&1 && echo "groupdel $1 success";
		return 0;
	fi;
}