#!/usr/bin/env bash

# Name: nodejs
# Desc: an auto web server installation tool
# Date: 2013-02-07 by garryshield

source ./const

# NVM
NVM=NVM
NVM_URL=https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh

echo "${NVM} installation"
echo "pleace input <Enter> twice to continue or <CTRL+C> to exit:"
read
read

wget -qO- ${NVM_URL} | bash

echo
echo

. ~/.bash_profile

nvm install node --latest-npm

echo
echo

nvm install --lts --latest-npm

nvm ls

# done
echo
echo
echo ================================================================================
echo "${NVM} config SUCCESS"
echo ================================================================================
echo
echo

exit 0