#!/usr/bin/env bash

# Name: vhost
# Desc: an auto web server installation tool
# Date: 2013-02-07 by garryshield

source ./const

echo "VHost installation";
echo '1: create nginx vhost config file';
echo '2: create php-fpm pool config file';
echo '4: create pure-ftp support'
echo '5: create memcached support'
echo '6: create redis support'
echo '7: create mariadb support'
echo 'pleace input <Enter> twice to continue or <CTRL+C> to exit:'
read
read

echo 'The options which with (*) prefix is required!';
echo '';

# Unique vhost ID
echo "Set an unique vhost ID";
echo "take the deamon name is cool";
echo "e.g. App URL is <www.domain.com>, you can take <www_domain_com> as ID";
echo -n "(*) ID:";
read vhost_id;
if [ "${vhost_id:+1}" != 1 ]; then
  echo "Error: Must input an unique ID for nginx vhost";
  exit 1;
fi;
echo "vhost_id: ${vhost_id}";

echo ;
echo "Set vhost user: (if not set take vhost ID ${vhost_id})";
echo "user will created if not exists";
echo -n "vhost user:";
read vhost_user;
vhost_user=${vhost_user:=${vhost_id}};
echo "vhost_user: ${vhost_user}";

echo ;
echo "Set vhost group: (if not set take pool user ${vhost_user})";
echo "for good manage assign all the www user to one group like 'www'!"
echo -n "vhost group:";
read vhost_group;
vhost_group=${vhost_group:=${vhost_user}}
echo "vhost_group: ${vhost_group}";

echo ;
echo "Set nginx root dir: (if not set take vhost ID ${vhost_id})";
echo "Set nginx root dir: (e.g. 'www_domain_com')";
echo "dir name under ${ToySitesPath}";
echo -n "(*) nginx root dir:";
read ngx_root;
ngx_root=${ngx_root:=${vhost_id}};
ngx_root=${ToySitesPath}/${ngx_root}
echo "ngx_root: ${ngx_root}";

if [ -d "${ngx_root}" ]; then
  echo "${ngx_root} already exists"
  exit 1
fi

echo ;
echo "Set nginx server name";
echo "e.g. 127.0.0.1 domain domain.com www.domain.com";
echo -n "(*) nginx server name:";
read ngx_server_name;
if [ "${ngx_server_name:+1}" != 1 ]; then
  echo "Error: Must input an server name for nginx vhost";
  exit 1;
fi;
echo "ngx_server_name: ${ngx_server_name}";

echo ;
echo "Set nginx listen: (if not set take 80)";
echo "if set as 80 and custom this vhost with SSL(following step)";
echo "it will be redefined as 443";
echo -n "nginx listen:";
read ngx_listen;
ngx_listen=${ngx_listen:=80};
echo "ngx_listen: ${ngx_listen}";


mkdir -p ${ngx_root}

. ./nginx group -v=1.14.2 -p=${ngx_root} -n=default -u=${vhost_user} -g=${vhost_group}
. ./nginx server -v=1.14.2 -p=${ngx_root} -n=default -s=www -P=${ngx_listen} -r=${ngx_root}/www --server-name="${ngx_server_name}"

. ./memcached group -v=1.5.12 -p=${ngx_root}
. ./memcached server -v=1.5.12 -p=${ngx_root} -P=11212 -u=${vhost_user} -g=${vhost_group}

. ./redis group -v=5.0.4 -p=${ngx_root}
. ./redis server -v=5.0.4 -p=${ngx_root} -P=6379

. ./elasticsearch group -v=6.7.0 -p=${ngx_root}
. ./elasticsearch server -v=6.7.0 -p=${ngx_root} -P=9200 -u=${vhost_user} -g=${vhost_group}

. ./pure-ftpd group -v=1.0.48 -p=${ngx_root}
. ./pure-ftpd server -v=1.0.48 -p=${ngx_root} -P=21

. ./php group -v=7.2.16 -p=${ngx_root} -n=default
. ./php server -v=7.2.16 -p=${ngx_root} -n=default -s=www -u=${vhost_user} -g=${vhost_group}

. ./php group -v=5.6.40 -p=${ngx_root} -n=default
. ./php server -v=5.6.40 -p=${ngx_root} -n=default -s=www -u=${vhost_user} -g=${vhost_group}

. ./php group -v=5.4.45 -p=${ngx_root} -n=default
. ./php server -v=5.4.45 -p=${ngx_root} -n=default -s=www -u=${vhost_user} -g=${vhost_group}

. ./mariadb group -v=10.3.13 -p=${ngx_root}
. ./mariadb server -v=10.3.13 -p=${ngx_root} -n=default -P=3306 -u=${vhost_user} -g=${vhost_group}

${ToySoftPath}/pure-ftpd-1.0.48/bin/pure-pw useradd ${vhost_user} -u ${vhost_user} -g ${vhost_group} -d ${ngx_root}/www -f ${ngx_root}/pure-ftpd-1.0.48/data/21/pure-ftpd.passwd
${ToySoftPath}/pure-ftpd-1.0.48/bin/pure-pw mkdb ${ngx_root}/pure-ftpd-1.0.48/data/21/pure-ftpd.pdb -f ${ngx_root}/pure-ftpd-1.0.48/data/21/pure-ftpd.passwd
${ToySoftPath}/pure-ftpd-1.0.48/bin/pure-pw show ${vhost_user} -f ${ngx_root}/pure-ftpd-1.0.48/data/21/pure-ftpd.passwd

chown -R ${vhost_user}:${vhost_group} ${ngx_root}/www